Adding cmd for running stat job via spark-submit
Merck/rdf2x pull request #1
Opened 2019-09-29 09:40 UTC by sudhan499

2019-09-30 12:57 UTC, prihoda requested changes
Great, thanks for the useful update 👍

Can you please check the comments that I added? Finally, can you update the version in `pom.xml` to <version>0.1.1</version>? Then I will be happy to merge the changes to master and create a new GitHub release.

Thanks!

2019-09-30 12:57 UTC, prihoda commented on src/main/java/com/merck/rdf2x/jobs/stats/StatsJob.java
> +    private long subjectURICount;
Can you use `Long` type and set it to `null` for these three count variables?

2019-09-30 12:57 UTC, prihoda commented on src/main/java/com/merck/rdf2x/jobs/stats/StatsJob.java
> +        log.info("Total Distinct Subject URIs: {}", subjectURICount);
Can you print the statistics only for the requested fields? You could set them to `null` and only print it if not `null`. It is a bit confusing to have them set to `0` if they are not requested.

2019-10-13 03:49 UTC, sudhan499 commented
Thanks a lot for taking time and reviewing my changes. I made suggested changes, please check.

2019-10-14 10:22 UTC, prihoda approved these changes

2019-10-14 10:23 UTC, merged